### ISSUE TITLE
HTML/XML code snippets are being modified

### ISSUE THREAD

**Issue by AmeliaBR** [asciidoctor/brackets-asciidoc-preview#20]
I'm not sure whether it is a general Asciidoctor issue, or a Brackets preview issue, but code snippets in the text relating to stylesheets are being mistaken for actual XML/HTML instructions and modified.

________________

The following Asciidoc source code:

```
[source, xml]
----    
<?xml-stylesheet href="style.css" type="text/css"?>
<?xml-stylesheet href="print.css" media="print" type="text/css"?>
----

[source, html]
----
<link href="style.css" rel="stylesheet" type="text/css">
<link href="print.css" rel="stylesheet" media="print" type="text/css">
----
```

Is compiled as:

```
<?xml-stylesheet href="style.css" title="style.css" type="text/css"?>
<?xml-stylesheet href="print.css" title="print.css" media="print" type="text/css"?>

<link href="style.css" title="style.css" rel="stylesheet" type="text/css">
<link href="print.css" title="print.css" rel="stylesheet" media="print" type="text/css">
```

Note the inserted `title` attributes.

**Comment by mojavelinux** [comment]
I strongly doubt this is Asciidoctor as it doesn't modify the content of source blocks. However, it could be the source highlighter doing it. Is the source highlighted in the preview? If so, it could be highlight.js that's doing it. Otherwise, it could be that Brackets is modifying the source somehow.

**Comment by nerk** [comment]
When exporting the file to a browser from the preview pane, the generated HTML is correct and no additional title attribute is added. @mojaveIinux I also thought that highlight.js might be responsible for that, because in the exported file, highlight.js is not used for source highlighting by default. 

However, I modified the code in such a way that in both cases (preview pane and exported file), the same highlighter is used. Interestingly enough, the results are the same no matter which highlighter is enabled: The preview pane shows the modified source, the exported HTML is correct.

I suspect it has something to to with enabled header-footer...

**Comment by nerk** [comment]
@AmeliaBR @mojavelinux 
Never mind, I found the problem in my code!

**Comment by AmeliaBR** [comment]
@nerk Great, thanks.  

One of those little bugs that will sneak by most testing, until someone has just the wrong content to trigger the regular expression.  

If you still want to have automatic tooltips for links (which is a neat feature), maybe the best solution would be to append a short script to the end of the generated HTML document.  The following should do it:

```javascript
var links = document.querySelectorAll("a[href]:not([title])");
                /* select all links that don't already have title attributes */
for (var i=0, n=links.length; i<n; i++ {
   links[i].setAttribute("title", links[i].getAttribute("href") );
   /* re-use the link URL as the tooltip */
})
```

**Comment by mojavelinux** [comment]
Great news!

> One of those little bugs that will sneak by most testing, until someone
has just the wrong content to trigger the regular expression.

That's why the open source model is so important and why community members
like you, willing to take the time to report issues & track down a
solution, are so important to us. Thanks!!!

**Comment by nerk** [comment]
@AmeliaBR Thanks for the code snippet!

**Comment by mojavelinux** [comment]
Actually, I think the best way to enable the tooltips in such a way that doesn't affect code snippets is to search for links that don't have `<pre>` (or `<code>`) as a parent. The part of the code that grabs links without a title is good, but then I'd go a step further and check that `<pre>` or `<code>` isn't a parent node. If there's a way to do this with the initial query, even better.

**Comment by AmeliaBR** [comment]
@mojavelinux 

That won't be required, because the script will run *after* code snippets have been escaped into `&lt;a&gt;` and so on.  There is no actual "link" there for querySelectorAll to select -- just a series of characters that look like code to us human beings.

**Comment by mojavelinux** [comment]
Very good point, @AmeliaBR.
